//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uslygi.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingAndTour
    {
        public int BookTour { get; set; }
        public Nullable<int> BookingId { get; set; }
        public Nullable<int> TourId { get; set; }
    
        public virtual booking booking { get; set; }
        public virtual TourForSales TourForSales { get; set; }
    }
}
