//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uslygi.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class check
    {
        public int CheckId { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> WorkerId { get; set; }
        public Nullable<int> TourId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual TourForSales TourForSales { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
