//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uslygi.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.booking = new HashSet<booking>();
            this.check = new HashSet<check>();
            this.Dogovor = new HashSet<Dogovor>();
        }
    
        public int ClientId { get; set; }
        public string ClientSecondName { get; set; }
        public string ClientName { get; set; }
        public string ClientMiddleName { get; set; }
        public Nullable<int> IdVidClient { get; set; }
        public Nullable<int> PassportId { get; set; }
        public Nullable<int> ZagranId { get; set; }
        public string ClientEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> booking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<check> check { get; set; }
        public virtual VidClient VidClient { get; set; }
        public virtual Pass Pass { get; set; }
        public virtual Zag Zag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dogovor> Dogovor { get; set; }
    }
}
