//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uslygi.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourForSales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TourForSales()
        {
            this.BookingAndTour = new HashSet<BookingAndTour>();
            this.check = new HashSet<check>();
            this.Price = new HashSet<Price>();
        }
    
        public int TourId { get; set; }
        public string TourName { get; set; }
        public string TourDescription { get; set; }
        public Nullable<int> AmountOfPeople { get; set; }
        public Nullable<System.DateTime> StartTourDate { get; set; }
        public Nullable<System.DateTime> EndTourDate { get; set; }
        public Nullable<int> AmountOfNights { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> HotelId { get; set; }
        public Nullable<int> TypeTourId { get; set; }
        public Nullable<int> VidTourId { get; set; }
        public Nullable<int> AvailabilityId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Availability Availability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingAndTour> BookingAndTour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<check> check { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual Hotel Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price> Price { get; set; }
        public virtual TypeTour TypeTour { get; set; }
        public virtual VidTour VidTour { get; set; }
    }
}
