//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uslygi.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourInfo
    {
        public int TourId { get; set; }
        public string TourName { get; set; }
        public Nullable<int> AmountOfNights { get; set; }
        public Nullable<int> AmountOfPeople { get; set; }
        public Nullable<System.DateTime> StartTourDate { get; set; }
        public Nullable<System.DateTime> EndTourDate { get; set; }
        public string TourDescription { get; set; }
        public string CountryName { get; set; }
        public string CityName { get; set; }
        public string HotelName { get; set; }
        public string TypeTourName { get; set; }
        public string VidTourName { get; set; }
        public string AvailabilityName { get; set; }
        public Nullable<int> CountPrice { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
